config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

admin.site.site_header = "SDE Indexing Helper Administration"  # default: "Django Administration"
admin.site.index_title = "SDE Indexing Helper"  # default: "Site administration"
admin.site.site_title = "SDE Indexing Helper"  # default: "Django site admin"

urlpatterns = [
    path("", include("sde_collections.urls", namespace="sde_collections")),
    path("feedback/", include("feedback.urls", namespace="feedback")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("sde_indexing_helper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("api-auth/", include("rest_framework.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sde_collections/urls.py
from django.urls import include, path
from rest_framework import routers

from environmental_justice.views import EnvironmentalJusticeRowViewSet

from . import views

router = routers.DefaultRouter()
router.register(r"collections", views.CollectionViewSet, basename="collection")
router.register(r"collections-read", views.CollectionReadViewSet, basename="collection-read")
router.register(r"candidate-urls", views.CandidateURLViewSet)
router.register(
    r"include-pattern-affected-urls", views.IncludePatternAffectedURLsViewSet, basename="include-pattern-affected-urls"
)
router.register(
    r"exclude-pattern-affected-urls", views.ExcludePatternAffectedURLsViewSet, basename="exclude-pattern-affected-urls"
)
router.register(
    r"title-pattern-affected-urls", views.TitlePatternAffectedURLsViewSet, basename="title-pattern-affected-urls"
)
router.register(
    r"documenttype-pattern-affected-urls",
    views.DocumentTypePatternAffectedURLsViewSet,
    basename="documenttype-pattern-affected-urls",
)
router.register(r"exclude-patterns", views.ExcludePatternViewSet)
router.register(r"include-patterns", views.IncludePatternViewSet)
router.register(r"title-patterns", views.TitlePatternViewSet)
router.register(r"document-type-patterns", views.DocumentTypePatternViewSet)
router.register(r"division-patterns", views.DivisionPatternViewSet)
router.register(r"environmental-justice", EnvironmentalJusticeRowViewSet)

app_name = "sde_collections"

urlpatterns = [
    path("", view=views.CollectionListView.as_view(), name="list"),
    path("sde-dashboard/", view=views.SdeDashboardView.as_view(), name="dashboard"),
    path("<int:pk>/", view=views.CollectionDetailView.as_view(), name="detail"),
    path(
        "api/collections/push_to_github/",
        views.PushToGithubView.as_view(),
        name="push-to-github",
    ),
    path(
        "api/indexing_instructions/",
        views.IndexingInstructionsView.as_view(),
        name="indexing_instructions",
    ),
    path("api/assign-division/<int:pk>/", views.CandidateURLViewSet.as_view({"post": "update_division"})),
    path(
        "delete-required-url/<int:pk>",
        view=views.RequiredUrlsDeleteView.as_view(),
        name="delete_required_url",
    ),
    path(
        "<int:pk>/candidate-urls",
        view=views.CandidateURLsListView.as_view(),
        name="candidate_urls",
    ),
    path(
        "exclude-pattern/<int:id>/",
        view=views.ExcludePatternAffectedURLsListView.as_view(),
        name="affected_urls",
    ),
    path(
        "include-pattern/<int:id>/",
        view=views.IncludePatternAffectedURLsListView.as_view(),
        name="affected_urls",
    ),
    path(
        "title-pattern/<int:id>/",
        view=views.TitlePatternAffectedURLsListView.as_view(),
        name="affected_urls",
    ),
    path(
        "document-type-pattern/<int:id>/",
        view=views.DocumentTypePatternAffectedURLsListView.as_view(),
        name="affected_urls",
    ),
    path(
        "consolidate/",
        view=views.WebappGitHubConsolidationView.as_view(),
        name="consolidate_db_and_github_configs",
    ),
    # List all CandidateURL instances: /candidate-urls/
    # Retrieve a specific CandidateURL instance: /candidate-urls/{id}/
    # Create a new CandidateURL instance: /candidate-urls/
    # Update an existing CandidateURL instance: /candidate-urls/{id}/
    # Delete an existing CandidateURL instance: /candidate-urls/{id}/
    path("api/", include(router.urls)),
    path(
        "candidate-urls-api/<str:config_folder>/",
        view=views.CandidateURLAPIView.as_view(),
        name="candidate-url-api",
    ),
    path("titles-and-errors/", views.TitlesAndErrorsView.as_view(), name="titles-and-errors-list"),
]

sde_indexing_helper/users/urls.py
from django.urls import path

from sde_indexing_helper.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

sde_collections/models/candidate_url.py
import hashlib
import os
from urllib.parse import urlparse

from django.db import models

from .collection import Collection
from .collection_choice_fields import Divisions, DocumentTypes
from .pattern import ExcludePattern, TitlePattern


class CandidateURLQuerySet(models.QuerySet):
    def with_exclusion_status(self):
        return self.annotate(
            excluded=models.Exists(
                ExcludePattern.candidate_urls.through.objects.filter(candidateurl=models.OuterRef("pk"))
            )
        )


class CandidateURLManager(models.Manager):
    def get_queryset(self):
        return CandidateURLQuerySet(self.model, using=self._db).with_exclusion_status()


class CandidateURL(models.Model):
    """A candidate URL scraped for a given collection."""

    collection = models.ForeignKey(Collection, on_delete=models.CASCADE, related_name="candidate_urls")
    url = models.CharField("URL")
    hash = models.CharField("Hash", max_length=32, blank=True, default="1")
    scraped_title = models.CharField(
        "Scraped Title",
        default="",
        blank=True,
        help_text="This is the original title scraped by Sinequa",
    )
    scraped_text = models.TextField(blank=True, null=True)
    generated_title = models.CharField(
        "Generated Title",
        default="",
        blank=True,
        help_text="This is the title generated based on a Title Pattern",
    )
    test_title = models.CharField(
        "Title on Test Server",
        default="",
        blank=True,
        help_text="This is the title present on Test Server",
    )
    production_title = models.CharField(
        "Title on Production Server",
        default="",
        blank=True,
        help_text="This is the title present on Production Server",
    )
    level = models.IntegerField("Level", default=0, blank=True, help_text="Level in the tree. Based on /.")
    visited = models.BooleanField(default=False)
    objects = CandidateURLManager()
    document_type = models.IntegerField(choices=DocumentTypes.choices, null=True)
    division = models.IntegerField(choices=Divisions.choices, null=True)
    inferenced_by = models.CharField(
        "Inferenced By",
        default="",
        blank=True,
        help_text="This keeps track of who inferenced document type",
    )
    is_pdf = models.BooleanField(
        "Is PDF",
        default=False,
        help_text="This keeps track of whether the given url is pdf or not",
    )
    present_on_test = models.BooleanField(
        "URL Present In Test Environment?",
        default=False,
        help_text="Helps keep track if the Current URL is present in test environment or not",
    )
    present_on_prod = models.BooleanField(
        "URL Present In Production?",
        default=False,
        help_text="Helps keep track if the Current URL is present in production or not",
    )

    class Meta:
        """Meta definition for Candidate URL."""

        verbose_name = "Candidate URL"
        verbose_name_plural = "Candidate URLs"
        ordering = ["url"]

    @property
    def fileext(self) -> str:
        # Parse the URL to get the path
        parsed_url = urlparse(self.url)
        path = parsed_url.path

        # Check for cases where the path ends with a slash or is empty, implying a directory or default file
        if path.endswith("/") or not path:
            return "html"

        # Extract the extension from the path
        extension = os.path.splitext(path)[1]

        # Default to .html if no extension is found
        if not extension:
            return "html"

        if extension.startswith("."):
            return extension[1:]
        return extension

    def splits(self) -> list[tuple[str, str]]:
        """Split the path into multiple collections."""
        parts = []
        part_string = ""
        for part in self.path.split("/"):
            if part:
                part_string += f"/{part}"
                parts.append((part_string, part))
        return parts

    @property
    def path(self) -> str:
        parsed = urlparse(self.url)
        path = f"{parsed.path}"
        if parsed.query:
            path += f"?{parsed.query}"
        return path

    def __str__(self) -> str:
        return self.url

    def save(self, *args, **kwargs):
        # Generate the hash based on the model values
        hash_string = f"{self.url}{self.generated_title}{self.document_type}"
        hash_value = hashlib.md5(hash_string.encode()).hexdigest()

        # Set the hash value
        self.hash = hash_value

        super().save(*args, **kwargs)


class ResolvedTitleBase(models.Model):
    title_pattern = models.ForeignKey(TitlePattern, on_delete=models.CASCADE)
    candidate_url = models.OneToOneField(CandidateURL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class ResolvedTitle(ResolvedTitleBase):
    resolved_title = models.CharField(blank=True, default="")

    class Meta:
        verbose_name = "Resolved Title"
        verbose_name_plural = "Resolved Titles"

    def save(self, *args, **kwargs):
        # Finds the linked candidate URL and deletes ResolvedTitleError objects linked to it
        ResolvedTitleError.objects.filter(candidate_url=self.candidate_url).delete()
        super().save(*args, **kwargs)


class ResolvedTitleError(ResolvedTitleBase):
    error_string = models.TextField(null=False, blank=False)
    http_status_code = models.IntegerField(null=True, blank=True)

sde_collections/models/collection_choice_fields.py
from django.db import models


class Divisions(models.IntegerChoices):
    ASTROPHYSICS = 1, "Astrophysics"
    BIOLOGY = 2, "Biological and Physical Sciences"
    EARTH_SCIENCE = 3, "Earth Science"
    HELIOPHYSICS = 4, "Heliophysics"
    PLANETARY = 5, "Planetary Science"
    GENERAL = 6, "General"

    @classmethod
    def lookup_by_text(cls, text: str) -> int | None:
        for choice in cls.choices:
            if choice[1].lower() == text.lower():
                return choice[0]
        return None


class UpdateFrequencies(models.IntegerChoices):
    DAILY = 1, "Daily"
    WEEKLY = 2, "Weekly"
    BIWEEKLY = 3, "Biweekly"
    MONTHLY = 4, "Monthly"


class DocumentTypes(models.IntegerChoices):
    IMAGES = 1, "Images"
    DATA = 2, "Data"
    DOCUMENTATION = 3, "Documentation"
    SOFTWARETOOLS = 4, "Software and Tools"
    MISSIONSINSTRUMENTS = 5, "Missions and Instruments"

    @classmethod
    def lookup_by_text(cls, text: str) -> int | None:
        for choice in cls.choices:
            if choice[1].lower() == text.lower():
                return choice[0]
        return None


class SourceChoices(models.IntegerChoices):
    ONLY_IN_ORIGINAL = 1, "Only in original"
    BOTH = 2, "Both"
    ONLY_IN_SINEQUA_CONFIGS = 3, "Only in Sinequa configs"


class ConnectorChoices(models.IntegerChoices):
    CRAWLER2 = 1, "crawler2"
    JSON = 2, "json"
    HYPERINDEX = 3, "hyperindex"
    NO_CONNECTOR = 4, "No Connector"

    @classmethod
    def lookup_by_text(cls, text: str) -> int | None:
        for choice in cls.choices:
            if choice[1].lower() == text.lower():
                return choice[0]
        return None


class CurationStatusChoices(models.IntegerChoices):
    NEEDS_SCRAPING = 1, "Needs Scraping"
    READY_TO_CURATE = 2, "Ready to Curate"
    BEING_CURATED = 3, "Being Curated"
    DELETE_COMBINE_COLLECTION = 7, "Delete/Combine Collection"
    NEEDS_RESCRAPING = 4, "Needs Rescraping"
    CURATED = 5, "Curated"
    GITHUB_PR_CREATED = 8, "GitHub PR Created"
    IN_PROD = 6, "In Production"

    @classmethod
    def get_status_string(cls, value):
        for choice in cls.choices:
            if choice[0] == value:
                return choice[1]
        return "N/A"


class WorkflowStatusChoices(models.IntegerChoices):
    RESEARCH_IN_PROGRESS = 1, "Research in Progress"
    READY_FOR_ENGINEERING = 2, "Ready for Engineering"
    ENGINEERING_IN_PROGRESS = 3, "Engineering in Progress"
    READY_FOR_CURATION = 4, "Ready for Curation"
    CURATION_IN_PROGRESS = 5, "Curation in Progress"
    CURATED = 6, "Curated"
    QUALITY_FIXED = 7, "Quality Fixed"
    SECRET_DEPLOYMENT_STARTED = 8, "Secret Deployment Started"
    SECRET_DEPLOYMENT_FAILED = 9, "Secret Deployment Failed"
    READY_FOR_LRM_QUALITY_CHECK = 10, "Ready for LRM Quality Check"
    READY_FOR_FINAL_QUALITY_CHECK = 11, "Ready for Quality Check"
    QUALITY_CHECK_FAILED = 12, "QC: Failed"
    QUALITY_CHECK_MINOR = 18, "QC: Minor Issues"
    QUALITY_CHECK_PERFECT = 13, "QC: Perfect"
    PROD_PERFECT = 14, "Prod: Perfect"
    PROD_MINOR = 15, "Prod: Minor Issues"
    PROD_MAJOR = 16, "Prod: Major Issues"
    MERGE_PENDING = 17, "Code Merge Pending"
    NEEDS_DELETE = 19, "Delete from Prod"

sde_collections/forms.py
from django import forms

from .models.collection import Collection, Comments, RequiredUrls


class RequiredUrlForm(forms.ModelForm):
    class Meta:
        model = RequiredUrls
        fields = ["url"]


class CollectionGithubIssueForm(forms.ModelForm):
    github_issue_link = forms.URLField()

    class Meta:
        model = Collection
        fields = [
            "github_issue_link",
        ]


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ["text"]

sde_indexing_helper/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {"username": {"unique": _("This username has already been taken.")}}


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

sde_indexing_helper/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("sde_collections:list")


user_redirect_view = UserRedirectView.as_view()

sde_indexing_helper/templates/sde_collections/collection_list.html
{% extends "layouts/base.html" %}
{% load static %}
{% load i18n %}
{% block title %}Collections{% endblock %}
{% block stylesheets %}
{% load humanize %}
    {{ block.super }}
    <link href="//cdn.datatables.net/v/bs4/jszip-3.10.1/dt-2.0.5/af-2.7.0/b-3.0.2/b-colvis-3.0.2/b-html5-3.0.2/b-print-3.0.2/cr-2.0.1/fc-5.0.0/fh-4.0.1/kt-2.12.0/r-3.0.2/rg-1.5.0/rr-1.5.0/sc-2.4.1/sp-2.3.1/sl-2.0.1/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/collections_list.css' %}">
{% endblock stylesheets %}
{% block content %}
    {% csrf_token %}
    <br>
    <h2 class="title">Welcome back!</h2>
    <table id="collection_table" class="table table-striped" style="width:100%" >
        <thead class="tableHeader">
            <tr>
                <th class="text-center noBorder" style="padding-right:25px !important">Name</th>
                <th class="text-center noBorder url-th" style="padding-right:25px !important">URL</th>
                <th class="text-center noBorder" style="padding-right:25px !important">Division</th>
                <th class="text-center noBorder" style="padding-right:25px !important">Candidate URLs</th>
                <th class="text-center noBorder" style="padding-right:25px !important">Workflow Status</th>
                <th class="text-center noBorder" style="padding-right:25px !important">Curator</th>
                <th class="text-center noBorder" style="padding-right:25px !important">Connector Type</th>

                <th class="hideDisplay"></th>
                <th class="hideDisplay"></th>
            </tr>
            <tr>
                <td class="filterRowBottom" ><input class="table_filter_row_input textBoxStyling" type="text" id="nameFilter" placeholder="Name" /></td>
                <td class="filterRowBottom url-td"><input class="table_filter_row_input textBoxStyling" type="text" id="urlFilter" placeholder="URL" /></td>
                <td class="filterRowBottom"><input class="table_filter_row_input textBoxStyling" type="text" id="divisionFilter" placeholder="Division" /></td>
                <td class="filterRowBottom"></td>
                <td class="filterRowBottom"><select id="collection-dropdown-4" class="select-dropdown selectStyling">
                    <option value="">SELECT</option>
                   {% for choice in workflow_status_choices %}
                       <option value="{{ choice }}" data-collection-id={{ collection.id }}>{{ choice.label }}</option>
                   {% endfor %}
                </select></td>
                <td class="filterRowBottom"><select id="collection-dropdown-5" class="select-dropdown selectStyling">
                    <option value="">SELECT</option>
                    {% for curator in curators %}
                    <option  value="{{ curator.pk }}" data-collection-id={{ collection.id }}>{{ curator.username }}</option>
                {% endfor %}
                </select></td>
                <td class="filterRowBottom"><input class="table_filter_row_input textBoxStyling" type="text" id="connectorTypeFilter" placeholder="Connector Type" /></td>
                <td class="hideDisplay"></td>
                <td class="hideDisplay"></td>
            </tr>
        </thead>

        <tbody>
            <div class="search-container">
                <label for="collectionSearch">Universal Search</label>
                <input type="text" id="collectionSearch" placeholder="Type to search..." class="table_filter_row_input textBoxStyling">
            </div>
            {% for collection in collections %}
                <tr id="{{ collection.id }}" data-config-folder="{{ collection.config_folder }}">
                    <td class="noBorder">
                        <a class="nameStyling" href="{% url 'sde_collections:detail' collection.pk %}">{{ collection.name }} <i class="material-icons">chevron_right</i></a>
                    </td>
                    <td class="url-td whiteText noBorder">
                        {% if collection.url %}
                            <div class="url-cell">
                                <span class="url" title="{{collection.url}}">{{ collection.url }}</span>
                                <a class="url-link" target="_blank" href=" {{ collection.url }} "> <i class="material-icons urlIcon">open_in_new</i></a></div>
                        {% endif %}
                    </td>
                    <td class="whiteText noBorder">{{ collection.get_division_display }}</td>
                    <td class="noBorder centerAlign">
                        <a href=" {% if collection.num_candidate_urls > 0 %} {% url 'sde_collections:candidate_urls' collection.pk %} {% endif %} "
                           class="btn btn-sm {% if collection.num_candidate_urls > 0 %}btn-primary {% else %}disabled{% endif %}candidateCount"
                           role="button">{{ collection.num_candidate_urls|intcomma }}</a>
                    </td>
                    <td class="noBorder">
                        <div class="dropdown workflow_status_dropdown"
                             data-match-pattern
                             remove_protocol
                             row
                             url>
                            <button class="btn {{ collection.workflow_status_button_color }} btn-sm dropdown-toggle"
                                    type="button"
                                    id="workflow-status-button-{{ collection.id }}"
                                    data-toggle="dropdown"
                                    aria-haspopup="true"
                                    aria-expanded="false">{{ collection.get_workflow_status_display }}</button>
                            <div class="dropdown-menu"
                                 aria-labelledby="workflow-status-button-{{ collection.id }}">
                                {% for choice in workflow_status_choices %}
                                    <a class="dropdown-item workflow_status_select" value="{{ choice }}" data-collection-id={{ collection.id }} >{{ choice.label }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </td>
                    <td class="noBorder">
                        <div class="dropdown curator_dropdown"
                             data-match-pattern
                             remove_protocol
                             row
                             url>
                            <button class="btn {% if collection.curated_by %} btn-success {% else %} btn-dark {% endif %} btn-sm dropdown-toggle"
                                    type="button"
                                    id="curator-button-{{ collection.id }}"
                                    data-toggle="dropdown"
                                    aria-haspopup="true"
                                    aria-expanded="false">{{ collection.curated_by }}</button>
                            <div class="dropdown-menu"
                                 aria-labelledby="curator-button-{{ collection.id }}">
                                {% for curator in curators %}
                                    <a  key="{{ curator.pk }}" class="dropdown-item curator_select" value="{{ curator.pk }}"  data-collection-id={{ collection.id }}
                                     >{{ curator.username }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </td>
                    <td class="whiteText noBorder">{{ collection.get_connector_display }}</td>
                    <td class="hideDisplay">{{ collection.workflow_status }}</td>
                    <td class="hideDisplay">{{ collection.curated_by_id }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div id="hideShowColumnsModal" class="modal pr-4 pl-4 pt-4 customizeColumnContainer">
        <div class="modalDialog">
            <div class="modalContent">
                <div class="modalHeader ">
                    <h5 class="modalTitle whiteText" id="hideShowColumnsModalTitle">Customize Columns</h5>
                    <p id="subTitle" class="whiteText">Attributes marked with a checkbox will be displayed in the table.</p>
                </div>
                <form id="hide_show_columns_form">
                    <div class="modalBody whiteText" id="modalBody">
                    </div>
                    <div class="modalFooter customizeColumnContainer">
                        <div type="submit" class="btn-prime hideShowSubmitButton" id="hideShowSubmitButton">Confirm</div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block javascripts %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="//cdn.datatables.net/v/bs4/jszip-3.10.1/dt-2.0.5/af-2.7.0/b-3.0.2/b-colvis-3.0.2/b-html5-3.0.2/b-print-3.0.2/cr-2.0.1/fc-5.0.0/fh-4.0.1/kt-2.12.0/r-3.0.2/rg-1.5.0/rr-1.5.0/sc-2.4.1/sp-2.3.1/sl-2.0.1/datatables.min.js"></script>
    <script src="{% static 'js/collection_list.js' %}"></script>
    <script src="{% static 'js/project.js' %}"></script>
{% endblock javascripts %}

sde_indexing_helper/templates/sde_collections/requiredurls_confirm_delete.html
{% extends "layouts/base.html" %}
{% block title %}
    Delete Required URL
{% endblock title %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}